"theme-mizudori" :
  use : "theme"

"date_format": "%b %d, %Y"

base_path: 'mizudori-international'
production_url: 'http://www.addhen.org'

widgets :

  analytics :
    use : google
    # -- tracking code for google analytics --
    tracking_id : ''
